### ISSUE TITLE
pre_text 可能为空

### ISSUE THREAD

**Issue by prnake** [Cerallin/hexo-filter-text-autospace#1]
输入文件为如下内容时，函数执行出错：
```
---
---
\`\`\`cpp
    #include <pthread.h> //引入，编译时加条件 -lpthread
\`\`\`
注
```

报错：
```
TypeError: Cannot read properties of undefined (reading 'search')
    at crossMatch (node_modules/hexo-filter-text-autospace/lib/filter.js:172:18)
    at filter (node_modules/hexo-filter-text-autospace/lib/filter.js:100:13)
```

可以通过跳过解决问题，但不清楚是否正确
```javascript
if (!matched || !pre_text || !suf_text)
      return;
```

**Comment by Cerallin** [comment]
虽然在`crossMatch`里校验是万无一失的，但是我还是想在这个函数外部处理好。

becddc705fd8897324460187af01cb3a7442f37b 试图解决这个bug，还请测试一下~

**Comment by prnake** [comment]
bug 解决了，感谢～
